/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blockchain.auth.mech.dev;

import java.util.Date;
import java.util.UUID;

public class RandomStringGeneration {

    public String createRandomString() {
        var timestampInMillis = new Date().getTime();
        return String.format("%s-%d", UUID.randomUUID(), timestampInMillis);
    }

}
