/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blockchain.auth.mech.signing;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;

public class Message {

    private byte[] messageBytes;

    public Message(String message) {
        messageBytes = message.getBytes(StandardCharsets.UTF_8);
    }

    public Message(byte[] message) {
        messageBytes = message;
    }

    public byte[] getMessageBytes() {
        return messageBytes;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Message that = (Message) o;
        return Arrays.equals(messageBytes, that.messageBytes);
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(messageBytes);
    }

}
